
# Network
listen_addresses = '*'
port = 5432

# Memory Settings
shared_buffers = 256MB

# network
listen_addresses = '*'
port = 5432

# memory settings
shared_buffers = 256MB

# wal settings (maximum write performance)
wal_level = minimal
wal_buffers = 16MB # smaller buffer = more frequent flushes
checkpoint_timeout = 2min # frequent checkpoints = less stalls
max_wal_size = 512MB # limit wal size
min_wal_size = 32MB # minimum wal size
checkpoint_completion_target = 0.9 # avoid faster flushes, spread it evenly to avoid heavy io
synchronous_commit = off # don't wait for wal writes
fsync = off # don't force disk writes
full_page_writes = off # don't log entire pages
max_connections = 100
max_wal_senders = 0 # no replication